/** @type {import('tailwindcss').Config} */
const colorVar = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

export default {
    darkMode: ['class', '[data-theme="dark"]'],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: colorVar('--color-primary-50'),
                    100: colorVar('--color-primary-100'),
                    200: colorVar('--color-primary-200'),
                    300: colorVar('--color-primary-300'),
                    400: colorVar('--color-primary-400'),
                    500: colorVar('--color-primary-500'),
                    600: colorVar('--color-primary-600'),
                    700: colorVar('--color-primary-700'),
                    800: colorVar('--color-primary-800'),
                    900: colorVar('--color-primary-900'),
                },
                gray: {
                    50: colorVar('--color-gray-50'),
                    100: colorVar('--color-gray-100'),
                    200: colorVar('--color-gray-200'),
                    300: colorVar('--color-gray-300'),
                    400: colorVar('--color-gray-400'),
                    500: colorVar('--color-gray-500'),
                    600: colorVar('--color-gray-600'),
                    700: colorVar('--color-gray-700'),
                    800: colorVar('--color-gray-800'),
                    900: colorVar('--color-gray-900'),
                },
                red: {
                    50: colorVar('--color-red-50'),
                    100: colorVar('--color-red-100'),
                    200: colorVar('--color-red-200'),
                    300: colorVar('--color-red-300'),
                    400: colorVar('--color-red-400'),
                    500: colorVar('--color-red-500'),
                    600: colorVar('--color-red-600'),
                    700: colorVar('--color-red-700'),
                },
                green: {
                    50: colorVar('--color-green-50'),
                    100: colorVar('--color-green-100'),
                    200: colorVar('--color-green-200'),
                    500: colorVar('--color-green-500'),
                    600: colorVar('--color-green-600'),
                    700: colorVar('--color-green-700'),
                },
                amber: {
                    50: colorVar('--color-amber-50'),
                    100: colorVar('--color-amber-100'),
                    200: colorVar('--color-amber-200'),
                    500: colorVar('--color-amber-500'),
                    600: colorVar('--color-amber-600'),
                    700: colorVar('--color-amber-700'),
                    800: colorVar('--color-amber-800'),
                },
                blue: {
                    50: colorVar('--color-blue-50'),
                    100: colorVar('--color-blue-100'),
                    200: colorVar('--color-blue-200'),
                    600: colorVar('--color-blue-600'),
                    700: colorVar('--color-blue-700'),
                },
                purple: {
                    50: colorVar('--color-purple-50'),
                    600: colorVar('--color-purple-600'),
                },
                white: colorVar('--color-white'),
                black: colorVar('--color-black'),
                sidebar: colorVar('--color-sidebar'),
                success: colorVar('--color-success'),
                warning: colorVar('--color-warning'),
                danger: colorVar('--color-danger'),
                background: colorVar('--color-background'),
                surface: colorVar('--color-surface'),
                'surface-muted': colorVar('--color-surface-muted'),
                border: colorVar('--color-border'),
                'text-primary': colorVar('--color-text-primary'),
                'text-muted': colorVar('--color-text-muted'),
            },
            fontFamily: {
                heading: ['Sora', 'DM Sans', 'sans-serif'],
                body: ['Inter', 'Nunito', 'sans-serif'],
                mono: ['JetBrains Mono', 'monospace'],
            },
        },
    },
    plugins: [],
}
